name: CI & Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  Android:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        nuget restore
        msbuild WheresMyKombucha/WheresMyKombucha.Android/WheresMyKombucha.Android.csproj $BUILD_VERBOSITY /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=QA /p:AndroidKeyStore=True /p:DefineConstants='"XAMARIN_UI_TESTS;__MOBILE__;__ANDROID__;QA_MODE;"'
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Rebuild /p:Configuration=Debug

  Android2:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android2
      run: |
        nuget restore
        msbuild WheresMyKombucha/WheresMyKombucha.Android/WheresMyKombucha.Android.csproj $BUILD_VERBOSITY /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=QA /p:AndroidKeyStore=True /p:DefineConstants='"XAMARIN_UI_TESTS;__MOBILE__;__ANDROID__;QA_MODE;"'

  iOS:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS
      run: |
        nuget restore
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Build /p:Platform=iPhoneSimulator /p:Configuration=Debug
