name: CI & Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what in there
      run: |
        ls
    - name: Show what it's inside
      run: |
        cd ..
        ls

  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        cd WheresMyKombucha
        nuget restore
        cd WheresMyKombucha.Android
        msbuild WheresMyKombucha.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug

  Android2:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android3
      run: |
        cd WheresMyKombucha
        nuget restore
        msbuild WheresMyKombucha.sln /verbosity:normal /t:Rebuild /p:Configuration=Debug

  iOS:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS
      run: |
        cd WheresMyKombucha
        nuget restore
        msbuild WheresMyKombucha.sln /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug

  iOS2:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS2
      run: |
        cd WheresMyKombucha
        nuget restore
        msbuild WheresMyKombucha.iOS/WheresMyKombucha.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
