name: CI & Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what in there
      run: |
        ls
    - name: Show what it's inside
      run: |
        cd ..
        ls

  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        nuget restore
        msbuild WheresMyKombucha/WheresMyKombucha.Android/WheresMyKombucha.Android.csproj $BUILD_VERBOSITY /t:Rebuild /p:Configuration=Debug
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Rebuild /p:Configuration=Debug

  Android2:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android2
      run: |
        nuget restore
        msbuild WheresMyKombucha/WheresMyKombucha.Android/WheresMyKombucha.Android.csproj $BUILD_VERBOSITY /t:Rebuild /p:Configuration=Debug

  Android3:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android3
      run: |
        nuget restore
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Rebuild /p:Configuration=Debug

  iOS:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS
      run: |
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
