name: CI & Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  build2:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Build1
      run: |
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Build /p:Platform=iPhoneSimulator /p:Configuration=Debug
  build3:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Build2
      run: |
        msbuild WheresMyKombucha/WheresMyKombucha.sln $BUILD_VERBOSITY /t:Build /p:Platform=iPhoneSimulator /p:Configuration=Debug
